language: ruby
rvm:
- 1.8.7
- 2.0.0
- 2.3.0
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
before_script: bundle exec puppet --version
script:
- bundle exec rake lint
- bundle exec rake validate
- bundle exec rake spec
env:
- PUPPET_VERSION='~> 3.8.0'
- PUPPET_VERSION='~> 4.3.0'
matrix:
  exclude:
  - rvm: 1.8.7
    env: PUPPET_VERSION='~> 4.3.0'
  - rvm: 2.3.0
    env: PUPPET_VERSION='~> 3.8.0'
  include:
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos-6-x64
    script: bundle exec rake beaker
deploy:
  provider: puppetforge
  user: hfm
  password:
    secure: tqOX2F2jKbgWaEdTeqEjWFG31g4XTFPHesg9jyr9ceFmsIDZd6ojAIJsbfSfOoRQQxW74wahkYY2kxo6H6H7SjIhlx9x9RWaXucd3WHubUJgxjCD33Wnc4jWy921pbtIS8bhmoFqCuaqbX+OtxNLg0ACorWSAOW5auQNG2N4uxdNTqJ/amT74nOuwr7sP+CAf6hUldzX8UFOJ37/8+3v1fQStpf2UlGje3lLNNRGswcJeJ8V955eUxGCOIASSvSv2kVvNBLVdTBsB8F9RhYwH5HXrlYhcKjaizCPOr3GXN19UG4pjcWEcVKI9CxQDI7xHuE+BDwQUMiYg3PTTU6AKjE3WAvoFnccYudjNI1k0+e79aBVhKeO4lRpa20JLUTswiJgQIsffD6DkXbswumZ0V8USvKEA334dR9j8F96OdvUCyGZmOy/f0KzdU6zkNagsHFnf2X4Q2KxEMIiTiKNP1D8tekLd3mNt36fiCX3DWq868K7H/r4kuBLYcJ9/nD4ccSDZXAHSMgBiCyL60PSSf+ppcD8zmudDb5X+7Uj8YKkr5ESBOfvYNBY/wgymRgwp4ZLXtKC05xFyg9pbo1nj5vKOTJIhCcKkdtkTMj4Zdk/AEdWyxvVozoWIPGcFgXPrH/ASTDjMCO+dAClEQKtlsN2RhdLXxZ/1ygnqbGc6bI=
  on:
    repo: hfm/puppet-embulk
    rvm: 2.0.0
    condition: $PUPPET_VERSION = '~> 3.8.0'
    tags: true
notifications:
  slack:
    secure: YQsy4yIZ60TX5gms6FyiNPpx8On4lpR4dDEbbWl9pxM0Pxyl3I+AQDO6uLIni8CZZDAWXLbACPzJVb1vlG1mnluBeleUfU3oUwXYvvkBpVu3Jeq7KutunFrSt/JMsb5diesS9RtYlDpCHIz0FXYByVFO4k/crIiiDtrMVG9LWnhNCmJlzAs2kA7Q7EHLT9XoS8FmIehB5DN5R+h46RoHqzLG6nzA8CrDfRsgSg/6671RSMaj6SqYZ3qZXVwAveLxaU0Ups8i3kCD6pZqY3ZnhTYeusQjizHdR0QvKluhuU2shpylBOsYgdW2qiSoD34JdTYpF8pguhUKgn1NlIAVs4ng1ZLU+qbjYEXgHZhPe3Ado7WFPmCMMhGkpmQrzdDb3RQuXYfwX+Yo65a4imW1Tb0Zh3YrMvwYPnQca93Ykym9y4i4VEy+ClFIeFQVcr4APcGIa/uX4KFdvbmKEEdbEj22v+ZPZSPXMz3S598niu2Q0ILT4/zehDkhnvYfJkZD/T0w6e8JNJYUf0+23G6eiDeZFdlztq+DAk76roSrY/luRR0A84QyG6Fe4mSSQm1A0XYMMEU0jbv1+m8tYIn7st9oStPgINQr6vd2X/w3YC8nzZD37ZT3LJ40y8SNXpBz6AcpTsg/qXRZelsztOI5RL0yt5iMumEZKGTknw/2uSQ=
