---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
rvm:
  - 2.4.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
      bundler_args: --without acceptance
    -
      env: CHECK=parallel_spec
      bundler_args: --without acceptance
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      bundler_args: --without acceptance
    -
      env: CHECK=beaker BEAKER_set=debian9 BEAKER_debug=true
      sudo: required
      services: docker
    -
      env: CHECK=beaker BEAKER_set=centos7 BEAKER_debug=true
      sudo: required
      services: docker
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
